baseURL = "http://localhost:1313/"
languageCode = "ja-jp"
title = "My Hugo Site"
theme = "ananke"

[params]
  author = "ティーチ"
  description = "私のこれまでの記事をまとめています。"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
