baseURL = "http://localhost:1313/"
languageCode = "ja-jp"
title = "My Blog"
theme = "ananke"

[params]
  author = "ティーチ"
  description = "私のこれまでの記事をまとめています。"
  custom_css = ["css/custom.css"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
